# Generated by Django 5.2.5 on 2025-08-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_whatsapp', models.TextField(default='Hola {nombre}, tu deuda actual en el buffet escolar es de ${deuda}.')),
            ],
        ),
        migrations.AlterField(
            model_name='alumno',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
